import { jsPDF } from "jspdf";
import { formatCurrency } from "./currency";

function header(document, title, subtitle) {
  document.setFillColor(8, 11, 22);
  document.rect(0, 0, 210, 297, "F");
  document.setFillColor(0, 212, 255);
  document.rect(0, 0, 210, 4, "F");
  document.setTextColor(255, 255, 255);
  document.setFontSize(22);
  document.text("NEXT GEAR", 18, 24);
  document.setTextColor(0, 212, 255);
  document.setFontSize(9);
  document.text("SECURE HARDWARE SYSTEMS", 18, 32);
  document.setTextColor(255, 255, 255);
  document.setFontSize(18);
  document.text(title, 18, 55);
  document.setTextColor(150, 166, 191);
  document.setFontSize(10);
  document.text(subtitle, 18, 63);
}

export function downloadBuildPdf({
  builderConfig,
  totalPrice,
  totalWattage,
  compatibilityStatus,
}) {
  const document = new jsPDF();
  header(
    document,
    "PC BUILD SPECIFICATION",
    "Generated by Next Gear Builder Studio",
  );
  let y = 82;
  document.setFontSize(11);
  Object.entries(builderConfig).forEach(([slot, component]) => {
    document.setTextColor(0, 212, 255);
    document.text(slot.toUpperCase(), 18, y);
    document.setTextColor(235, 240, 248);
    document.text(component?.name || "Not selected", 62, y);
    y += 11;
  });
  document.setDrawColor(45, 63, 91);
  document.line(18, y + 2, 192, y + 2);
  document.setTextColor(150, 166, 191);
  document.text("TOTAL ESTIMATE", 18, y + 17);
  document.setTextColor(255, 255, 255);
  document.setFontSize(15);
  document.text(formatCurrency(totalPrice), 125, y + 17);
  document.setFontSize(10);
  document.setTextColor(150, 166, 191);
  document.text(`Power draw: ${totalWattage}W`, 18, y + 29);
  document.text(
    `Compatibility: ${compatibilityStatus.isCompatible ? "Verified" : "Issues detected"}`,
    18,
    y + 39,
  );
  document.save("next-gear-build-specification.pdf");
}

export function downloadInvoicePdf(order) {
  const document = new jsPDF();
  header(
    document,
    `INVOICE #${order.id}`,
    "Order confirmation and hardware invoice",
  );
  document.setTextColor(150, 166, 191);
  document.setFontSize(10);
  document.text(
    `Date: ${order.date || new Date().toISOString().slice(0, 10)}`,
    18,
    78,
  );
  document.text(
    `Customer: ${order.customer || order.email || "Customer"}`,
    18,
    86,
  );
  let y = 105;
  document.setTextColor(0, 212, 255);
  document.text("ITEM", 18, y);
  document.text("QTY", 142, y);
  document.text("TOTAL", 168, y);
  y += 9;
  document.setTextColor(235, 240, 248);
  (order.items || []).forEach((item) => {
    document.text(String(item.name).slice(0, 48), 18, y);
    document.text(String(item.quantity), 144, y);
    document.text(formatCurrency(item.price * item.quantity, 0), 168, y);
    y += 9;
  });
  document.setDrawColor(45, 63, 91);
  document.line(18, y + 3, 192, y + 3);
  document.setTextColor(255, 255, 255);
  document.setFontSize(14);
  document.text(`TOTAL ${formatCurrency(order.total)}`, 18, y + 18);
  document.setFontSize(10);
  document.setTextColor(150, 166, 191);
  document.text(`Status: ${order.status || "Processing"}`, 18, y + 30);
  document.text(
    `Tracking: ${order.trackingNumber || "Assigned after dispatch"}`,
    18,
    y + 39,
  );
  document.save(`next-gear-invoice-${order.id}.pdf`);
}
